{% set version = "0.12.0" %}
{% set name = "seaborn" %}
{% set sha256 = "893f17292d8baca616c1578ddb58eb25c72d622f54fc5ee329c8207dc9b57b23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<37]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ cdt('mesa-libgl') }}  # [linux]

  host:
    - pip
    - python
    - setuptools
    - wheel
    - flit-core >=3.2,<4

  run:
    - python
    - numpy >=1.17
    # matplotlib 3.6.1 incompatible with latest master for 0.12.0
    # https://github.com/mwaskom/seaborn/issues/3072
    - matplotlib >=3.1,!=3.6.1
    - pandas >=0.25
    - typing_extensions  # [py<38]

  run_constrained:
    - scipy >=1.3
    - statsmodels >=0.10

test:
  imports:
    - seaborn
    - seaborn.colors
    - seaborn.external
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://seaborn.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  license_url: https://github.com/mwaskom/seaborn/blob/master/LICENSE.md
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  dev_url: https://github.com/mwaskom/seaborn
  doc_url: https://seaborn.pydata.org
  doc_source_url: https://github.com/mwaskom/seaborn/blob/master/doc/index.rst

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
