{% set version = "0.11.2" %}
{% set name = "seaborn" %}
{% set sha256 = "cf45e9286d40826864be0e3c066f98536982baf701a7caa386511792d61ff4f6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  build:
    - {{ cdt('mesa-libgl') }}  # [linux]

  run:
    - python >=3.6
    - numpy >=1.16
    - matplotlib >=3.0
    - scipy >=1.2
    - pandas >=0.24
    - statsmodels >=0.9

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://seaborn.pydata.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  dev_url: https://github.com/mwaskom/seaborn
  doc_url: https://seaborn.pydata.org
  doc_source_url: https://github.com/mwaskom/seaborn/blob/master/doc/index.rst

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
