{% set version = "0.13.2" %}
{% set name = "seaborn" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93e60a40988f4d65e9f4885df477e2fdaff6b73a9ded434c1ab356dd57eefff7

build:
  number: 0
  skip: true  # [py<37]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ cdt('mesa-libgl') }}  # [linux]
  host:
    - pip
    - python
    - flit-core >=3.2,<4
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.20,!=1.24.0
    - matplotlib-base >=3.4,!=3.6.1
    - pandas >=1.2
  run_constrained:
    - scipy >=1.7
    - statsmodels >=0.12

test:
  imports:
    - seaborn
    - seaborn.colors
    - seaborn.external
    - seaborn.objects
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://seaborn.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  dev_url: https://github.com/mwaskom/seaborn
  doc_url: https://seaborn.pydata.org

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
