{% set version = "0.13.2" %}
{% set name = "seaborn" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93e60a40988f4d65e9f4885df477e2fdaff6b73a9ded434c1ab356dd57eefff7

build:
  number: 1
  skip: true  # [py<38]
  script: python -m pip install . --no-deps --ignore-installed --no-build-isolation

requirements:
  build:
    - {{ cdt('mesa-libgl') }}  # [linux]
  host:
    - pip
    - python
    - flit-core >=3.2,<4
  run:
    - python
    - numpy >=1.20,!=1.24.0
    - matplotlib-base >=3.4,!=3.6.1
    - pandas >=1.2
  run_constrained:
    - scipy >=1.7
    - statsmodels >=0.12

test:
  source_files:
    - tests
  imports:
    - seaborn
    - seaborn.colors
    - seaborn.external
    - seaborn.objects
  commands:
    - pip check
    # test uses numpy 2 depricated APIs and fails
    - pytest tests -vv -k "not test_weights and not test_1d_row_wrapped and not test_1d_column_wrapped"
  requires:
    - pip
    - pytest
    - scipy >=1.7
    - statsmodels >=0.12
# Re-adding matplotlib here so qt backend is used instead of tk to avoid `cannot find tcl` error
    - matplotlib

about:
  home: https://seaborn.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Statistical data visualization
  description: |
    Seaborn is a Python visualization library based on matplotlib. It
    provides a high-level interface for drawing attractive statistical graphics.
  dev_url: https://github.com/mwaskom/seaborn
  doc_url: https://seaborn.pydata.org

extra:
  recipe-maintainers:
    - msarahan
    - r-jain1
    - croth1
