travis:
  secure:
    BINSTAR_TOKEN: AyLqqZpUG+ZnbYPfb2sllDiIkSIP4HSyzQ4QC13UU4UJKNN7rzvUAjDqzxPGssgni2FLQIrEldIB9fK9DYsOOOVS3aGt7z+lK6b5CX96+0PqEjHE20vX+9Xo18YAfj/JICvosDVCQFQiWi7FMOjQCWg+VogqUkW5EcRk8mKK0PsurczMzbmfLVLe4+hnAOARblKe2cExctzkbvilL3zToTh/1TJRvOky/qJl7xuX2EU91JuCJz2EfuOuBrohQdL+R0Kzeto2h03f01oKoLgzLdQ7eN9DfYdYWSZExGUbO2ijzDiZkWxa+LsolP4Vxdu6e1ZG/U1s7ZNjipuQidkkZBIbzU9gn9DGCIuxsqMznI4B2U5wLn7cxOlztJwZsyo7NK6UR9szXp5vot2AqW/jQJwcGpQC0zU8glbjMCyUQhIFdaTtRxvb3mBGFtwDV20CpLn3RLwIM4s76REm03jvIMgg/v3XFFQYPS5/TTW+3rnuPR3zbRyX0OIJnPkXO9CCGJlyYPoQGh6nardjBRRtHCv9MhUgrQqBU6QJSKPwTVEXWygc/iYDIeOd4yGqtRTQATmLTJj/ieYdrlWupfGmYdvNF4IRswK4YOBfpPgqQPZpVCpLKUap6Tb22axyX0xfvbJqXT3pAjsZKpp1MI2+oEqSK8F85jrsq1IxrM3zxsc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
