travis:
  secure:
    BINSTAR_TOKEN: VimunpiuV8fFx7Q9oG6H2upg14wBft0zJW7iEWkzT7HaKvpnpvVOgEnovQnOnyWbf6exBO/0QYdxxEBNgjVecEeTve/E+ni0WxmBm9LfgUy6HKAnIOnzMf2gxk95OeKsc4AH26q4eccPgdAtmB4ESgrAA9aRSzs6r7EZxbP7/usgwfYQgkdY6eJdDWw8TzFzHQpeb61MMYH5kMOthNX5IXhBmtunWJF1Rx4sYkDzwI+bxXEqtEYLGrWr6GuhRnw/tmR+RfjGIYCiMZX/SEWaxyZiSc/22UwYm2jWCwKoK0yox1IBc/w4IoLhkbTukUX4E5IhApWjXYVuOiR5IzEQdV0Jo96cyDaLktmisNp7DyB3TAU0mlXfmSPCtJwkJ7J2yKZKAmfStTMPojdeclHZxMHQN78GBMFRTqgxsuN8BMg97hsNUvewLzQupwaS7l0Ii/G0eRR5ZwB4W1WfSpcAN9Q1MEMsKCGoL1lWFc3Q6E4qGpbgezI2TzQk3K5P3/W8ly0HhfBXuXzZ9/Q0VbMQDd0KaSOhFIMf/IxRSm/Yx9gj62QDxNwUlof+WYk2d7Q9ZFwQ5O3/pCYs7Rsemtytvmtmga/Diqv/ddf4boNoQsHCnsKBI/YpVYtku670ApJT5kTqR2Ez+yT2nchYt8v0IPoiCYuX8hT4eNKdFAJodYI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
